/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import DAO.bairroDAO;
import DAO.cidadeDAO;
import DAO.produtoDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nfbrentano
 */
public class AlterarBairro extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPais
     */
    public AlterarBairro() {
        initComponents();
        this.preencheJComboBoxBairro();
    }

    /**
     * Preenche o campo de bairros na tela com as informações cadastradas no
     * banco de dados
     */
    public void preencheJComboBoxBairro() {
        ResultSet result;
        String sql = "SELECT * FROM bairro ORDER BY nome";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jCBbairro.addItem(result.getString("nome"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Preenche o campo de cidades na tela com as informações cadastradas no
     * banco de dados
     */
    public void preencheJComboBoxCidade() {
        ResultSet result;
        String sql = "SELECT * FROM cidade ORDER BY nome";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jCBcidade.addItem(result.getString("nome"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Insere dados na tela referentes ao nome selecionado na busca
     *
     * @param id do bairro cadastrado
     */
    public void preencheCadastro(String nome) {
        ResultSet result;
        String sql = "SELECT b.idbairro AS id, b.nome AS bairro, c.nome AS cidade FROM bairro b INNER JOIN cidade c ON (c.idcidade = b.cidade_idcidade) WHERE b.nome ='" + nome + "';";
        this.jCBcidade.removeAllItems();
        this.preencheJComboBoxCidade();
        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            System.out.println(sql);
            System.out.println("oi oi");
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jTidBairro.setText(result.getString("id"));
                JtnomeBairro.setText(result.getString("bairro"));
                jCBcidade.setSelectedItem(result.getString("cidade"));

            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBalterarBairro = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTidBairro = new javax.swing.JTextField();
        jCBcidade = new javax.swing.JComboBox<>();
        JtnomeBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCBbairro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Bairro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar Bairro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 135, -1));

        jLabel2.setText("ID* :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, -1, -1));

        jLabel3.setText("Nome do Bairro* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jBalterarBairro.setText("Alterar");
        jBalterarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel4.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jTidBairro.setEditable(false);
        jTidBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTidBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

        jCBcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBcidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jCBcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        JtnomeBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtnomeBairroActionPerformed(evt);
            }
        });
        getContentPane().add(JtnomeBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, -1));

        jLabel5.setText("Cidade*:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jCBbairro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBbairroItemStateChanged(evt);
            }
        });
        getContentPane().add(jCBbairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, -1));

        jLabel6.setText("Bairro* :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBalterarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarBairroActionPerformed
        //recebe os dados digitados na tela
        String id = jTidBairro.getText();
        String bairro = JtnomeBairro.getText();
        String cidade = (String) jCBcidade.getSelectedItem();
        cidadeDAO.selectCidadeId(cidade);
        String obrigatorio = "";
        boolean controle = false;
        //validação
        if (id.equals("")) {
            obrigatorio = obrigatorio + "\n - ID";
            controle = true;
        }
        if (bairro.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome do Bairro";
            controle = true;
        }
        if (cidade.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome da Cidade";
            controle = true;
        }
        if (controle == false) {
            //atualiza cadastro no banco de dados
            bairroDAO.updateCadastroBairro(bairro, cidadeDAO.selectCidadeId(cidade), id);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }


    }//GEN-LAST:event_jBalterarBairroActionPerformed

    private void jCBcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBcidadeActionPerformed

    private void JtnomeBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtnomeBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtnomeBairroActionPerformed

    private void jTidBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidBairroActionPerformed

    private void jCBbairroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBbairroItemStateChanged
        //adiciona os dados do cadastro a ser alterado na tela
        preencheCadastro((String) jCBbairro.getSelectedItem());


    }//GEN-LAST:event_jCBbairroItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtnomeBairro;
    private javax.swing.JButton jBalterarBairro;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JComboBox<String> jCBbairro;
    private javax.swing.JComboBox<String> jCBcidade;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTidBairro;
    // End of variables declaration//GEN-END:variables
}

