/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import DAO.estadoDAO;
import DAO.paisDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nfbrentano
 */
public class AlterarPais extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPais
     */
    public AlterarPais() {
        initComponents();
        this.preencheJComboBoxPais();
    }

    /**
     * preenche o combobox de paises fazendo um select na base de dados
     */
    public void preencheJComboBoxPais() {
        ResultSet result;
        String sql = "SELECT * FROM pais";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jCBpais.addItem(result.getString("nome"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * preenche o cadastro da tela com informações do banco utilizando filtro
     * com a variavel de nome
     *
     * @param nome varivel utilziada no filtro
     */
    public void preencheCadastro(String nome) {
        ResultSet result;
        String sql = "SELECT * FROM pais WHERE nome ='" + nome + "';";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            System.out.println(sql);
            System.out.println("oi oi");
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jTnomePais.setText(result.getString("nome"));
                jTid.setText(result.getString("idpais"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTnomePais = new javax.swing.JTextField();
        jBsalvarPais = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jCBpais = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Pais");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar Pais");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 112, -1));

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setText("Nome do Pais* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTnomePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomePaisActionPerformed(evt);
            }
        });
        getContentPane().add(jTnomePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        jBsalvarPais.setText("Salvar");
        jBsalvarPais.setDefaultCapable(false);
        jBsalvarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalvarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jCBpais.setMinimumSize(new java.awt.Dimension(6, 20));
        jCBpais.setPreferredSize(new java.awt.Dimension(6, 20));
        jCBpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBpaisItemStateChanged(evt);
            }
        });
        getContentPane().add(jCBpais, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 150, -1));

        jLabel4.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel5.setText("Pais* :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jTid.setEditable(false);
        getContentPane().add(jTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTnomePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomePaisActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarPaisActionPerformed
        //recebe dados da tela
        String id = jTid.getText();
        String nome = jTnomePais.getText();
        String obrigatorio = "";
        boolean controle = false;
        //validação
        if (id.equals("")) {
            obrigatorio = obrigatorio + "\n - ID";
            controle = true;
        }
        if (nome.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome do Pais";
            controle = true;
        }
        if (controle == false) {
            //atualiza o cadastro de paises e atualiza o combobox de paises na tela
            paisDAO.updateCadastroPais(nome, id);
            this.preencheJComboBoxPais();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }
    }//GEN-LAST:event_jBsalvarPaisActionPerformed

    private void jCBpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBpaisItemStateChanged
        String obrigatorio = "";
        boolean controle = false;
        //validação

        if (jCBpais.getSelectedItem().equals("")) {
            obrigatorio = obrigatorio + "\n - NOME";
            controle = true;

        }
        if (controle == false) {
            //preenche os dados na tela com uso da função preencheCadastro e filtra 
            //pelo campo na tela de combobox de paises
            preencheCadastro((String) jCBpais.getSelectedItem());

        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }
        // TODO add your handling code here:    }//GEN-LAST:event_jCBpaisItemStateChanged
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvarPais;
    private javax.swing.JComboBox<String> jCBpais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnomePais;
    // End of variables declaration//GEN-END:variables
}
