/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import DAO.bairroDAO;
import DAO.cidadeDAO;
import DAO.estadoDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nfbrentano
 */
public class CadastrarCidade extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPais
     */
    public CadastrarCidade() {
        initComponents();
        this.preencheID();
        this.preencheJComboBoxEstado();
    }
    
    //preenche o combobox com informaçoes de estados do banco
    public void preencheJComboBoxEstado() {
        ResultSet result;
        String sql = "SELECT * FROM estado ORDER BY sigla";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jCBestado.addItem(result.getString("sigla"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * preenche o campo de id da tela com um select e adiciona 1 para cadastrar 
     * o proximo id disponivel
     */
public void preencheID() {
        ResultSet result;
        String sql = "select max(idcidade+1) from cidade";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jTidCidade.setText((result.getString("max")));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTidCidade = new javax.swing.JTextField();
        jTnomeCidade = new javax.swing.JTextField();
        jBsalvarCidade = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCBestado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cidade");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Cidade");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 27, 134, -1));

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Nome do Cidade* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTidCidade.setEditable(false);
        jTidCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTidCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 85, 135, -1));

        jTnomeCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTnomeCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, -1));

        jBsalvarCidade.setText("Salvar");
        jBsalvarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalvarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel9.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        getContentPane().add(jCBestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, -1));

        jLabel4.setText("Estado* :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTidCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidCidadeActionPerformed

    private void jTnomeCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeCidadeActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
       dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarCidadeActionPerformed
        //variaveis que buscam informaçoes da tela
        String id = jTidCidade.getText();
        String cidade = jTnomeCidade.getText();
        String estado = (String) jCBestado.getSelectedItem();
        estadoDAO.selectEstadoId(estado);
        System.out.println(estadoDAO.selectEstadoId(estado));
        String obrigatorio = "";
        boolean controle = false;
        //validação
        if (cidade.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome da Cidade";
            controle = true;
        }
        if (estado.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome do Estado";
            controle = true;
        }
        if (controle == false) {
            // insere informações no banco de dados sobre cidades
            cidadeDAO.insertCadastroCidade(id, cidade, estadoDAO.selectEstadoId(estado));
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }

    }//GEN-LAST:event_jBsalvarCidadeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvarCidade;
    private javax.swing.JComboBox<String> jCBestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTidCidade;
    private javax.swing.JTextField jTnomeCidade;
    // End of variables declaration//GEN-END:variables
}
