/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

/**
 *
 * @author nfbrentano
 */
public class CadastroEnderecos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroEnderecos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBsair = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBcadastrarPais = new javax.swing.JButton();
        jBcadastrarEstado = new javax.swing.JButton();
        jBcadastrarBairro = new javax.swing.JButton();
        jBcadastrarCidade = new javax.swing.JButton();
        jBalterarBairro = new javax.swing.JButton();
        jBalterarCidade1 = new javax.swing.JButton();
        jBalterarEstado1 = new javax.swing.JButton();
        jBalterarPais = new javax.swing.JButton();
        jBcadastrarRua = new javax.swing.JButton();
        jBalterarRua = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Endereços");
        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(900, 510));
        setPreferredSize(new java.awt.Dimension(900, 510));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 510));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImagemEndereco.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, -1, 469));

        jLabel5.setText("Cidade :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        getContentPane().add(jBsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 70, -1));

        jLabel6.setText("Bairro :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        jLabel7.setText("Tela de Cadastro de Endereços");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 33, -1, -1));

        jLabel9.setText("Pais :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel10.setText("Estado :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jBcadastrarPais.setText("Cadastrar Pais");
        jBcadastrarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jBcadastrarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 190, -1));

        jBcadastrarEstado.setText("Cadastrar Estado");
        jBcadastrarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jBcadastrarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 190, -1));

        jBcadastrarBairro.setText("Cadastrar Bairro");
        jBcadastrarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jBcadastrarBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 190, -1));

        jBcadastrarCidade.setText("Cadastrar Cidade");
        jBcadastrarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jBcadastrarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 190, -1));

        jBalterarBairro.setText("Alterar Bairro");
        jBalterarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 190, -1));

        jBalterarCidade1.setText("Alterar Cidade");
        jBalterarCidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarCidade1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 190, -1));

        jBalterarEstado1.setText("Alterar Estado");
        jBalterarEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarEstado1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 190, -1));

        jBalterarPais.setText("Alterar Pais");
        jBalterarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 190, -1));

        jBcadastrarRua.setText("Cadastrar Rua");
        jBcadastrarRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarRuaActionPerformed(evt);
            }
        });
        getContentPane().add(jBcadastrarRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 190, -1));

        jBalterarRua.setText("Alterar Rua");
        jBalterarRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarRuaActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 190, -1));

        jLabel8.setText("Rua :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * abaixo as funções abrem as telas de cadastros 
 * @param evt 
 */
    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBcadastrarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarPaisActionPerformed
        new CadastrarPais().setVisible(true);
    }//GEN-LAST:event_jBcadastrarPaisActionPerformed

    private void jBalterarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarPaisActionPerformed
        new AlterarPais().setVisible(true);
    }//GEN-LAST:event_jBalterarPaisActionPerformed

    private void jBcadastrarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarEstadoActionPerformed
        new CadastrarEstado().setVisible(true);
    }//GEN-LAST:event_jBcadastrarEstadoActionPerformed

    private void jBcadastrarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarCidadeActionPerformed
        new CadastrarCidade().setVisible(true);
    }//GEN-LAST:event_jBcadastrarCidadeActionPerformed

    private void jBcadastrarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarBairroActionPerformed
        new CadastrarBairro().setVisible(true);
    }//GEN-LAST:event_jBcadastrarBairroActionPerformed

    private void jBalterarEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarEstado1ActionPerformed
        new AlterarEstado().setVisible(true);
    }//GEN-LAST:event_jBalterarEstado1ActionPerformed

    private void jBalterarCidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarCidade1ActionPerformed
        new AlterarCidade().setVisible(true);
    }//GEN-LAST:event_jBalterarCidade1ActionPerformed

    private void jBalterarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarBairroActionPerformed
        new AlterarBairro().setVisible(true);
    }//GEN-LAST:event_jBalterarBairroActionPerformed

    private void jBcadastrarRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarRuaActionPerformed
        new CadastrarRua().setVisible(true);
    }//GEN-LAST:event_jBcadastrarRuaActionPerformed

    private void jBalterarRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarRuaActionPerformed
        new AlterarRua().setVisible(true);
    }//GEN-LAST:event_jBalterarRuaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterarBairro;
    private javax.swing.JButton jBalterarCidade1;
    private javax.swing.JButton jBalterarEstado1;
    private javax.swing.JButton jBalterarPais;
    private javax.swing.JButton jBalterarRua;
    private javax.swing.JButton jBcadastrarBairro;
    private javax.swing.JButton jBcadastrarCidade;
    private javax.swing.JButton jBcadastrarEstado;
    private javax.swing.JButton jBcadastrarPais;
    private javax.swing.JButton jBcadastrarRua;
    private javax.swing.JButton jBsair;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
