/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import DAO.cidadeDAO;
import DAO.estadoDAO;
import DAO.paisDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nfbrentano
 */
public class CadastrarEstado extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPais
     */
    public CadastrarEstado() {
        initComponents();
        this.preencheID();
        this.preencheJComboBoxPais();
    }
    /**
     * preenche o id adicionando 1 para ser o proximo id disponivel de cadastro
     */
    public void preencheID() {
        ResultSet result;
        String sql = "select max(idestado+1) from estado";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jTidEstado.setText((result.getString("max")));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();

        }
    }
    /**
     * preenche o combobox com informaçoes de paises do banco
     * de dados
     */
public void preencheJComboBoxPais() {
        ResultSet result;
        String sql = "SELECT * FROM pais ORDER BY nome";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jCBpais.addItem(result.getString("nome"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTidEstado = new javax.swing.JTextField();
        jTsiglaEstado = new javax.swing.JTextField();
        jBsalvarEstado = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTnomeEstado = new javax.swing.JTextField();
        jCBpais = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Estado");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 20, 145, -1));

        jLabel2.setText("ID* :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("Sigla do Estado *:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jTidEstado.setEditable(false);
        jTidEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTidEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, -1));

        jTsiglaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsiglaEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTsiglaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, -1));

        jBsalvarEstado.setText("Salvar");
        jBsalvarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalvarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel9.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jLabel4.setText("Nome do Estado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        getContentPane().add(jTnomeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, -1));

        getContentPane().add(jCBpais, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));

        jLabel5.setText("Pais* :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTidEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidEstadoActionPerformed

    private void jTsiglaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsiglaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsiglaEstadoActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarEstadoActionPerformed
        //variaveis criadas para buscar as informaçoes na tela
        String id = jTidEstado.getText();
        String estado = jTnomeEstado.getText();
        String sigla = jTsiglaEstado.getText();
        String pais = (String) jCBpais.getSelectedItem();
        paisDAO.selectPaisId(pais);
        System.out.println(paisDAO.selectPaisId(pais));
        String obrigatorio = "";
        boolean controle = false;
        //validação
        if (estado.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome do Bairro";
            controle = true;
        }
        if (sigla.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome da Cidade";
            controle = true;
        }
        if (pais.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome da Cidade";
            controle = true;
        }
        if (controle == false) {
            //função que insere informaçoes de cadastro de estado
            estadoDAO.insertCadastroEstado(id, sigla, estado, paisDAO.selectPaisId(pais) );
            dispose();
            
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }    }//GEN-LAST:event_jBsalvarEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvarEstado;
    private javax.swing.JComboBox<String> jCBpais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTidEstado;
    private javax.swing.JTextField jTnomeEstado;
    private javax.swing.JTextField jTsiglaEstado;
    // End of variables declaration//GEN-END:variables
}
