/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import DAO.cidadeDAO;
import DAO.estadoDAO;
import DAO.paisDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nfbrentano
 */
public class CadastrarPais extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPais
     */
    public CadastrarPais() {
        initComponents();
        this.preencheID();
    }
 /**
  * insere o id na tela adidionando 1 para ser o proximo id disponivel no 
  * cadastro
  */
    public void preencheID() {
        ResultSet result;
        String sql = "select max(idpais+1) from pais";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jTidPais.setText((result.getString("max")));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTidPais = new javax.swing.JTextField();
        jTnomePais = new javax.swing.JTextField();
        jBsalvarPais = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Pais");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Pais");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 29, 112, -1));

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setText("Nome do Pais* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jTidPais.setEditable(false);
        jTidPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jTidPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 135, -1));

        jTnomePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomePaisActionPerformed(evt);
            }
        });
        getContentPane().add(jTnomePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 135, -1));

        jBsalvarPais.setText("Salvar");
        jBsalvarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalvarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel9.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTidPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidPaisActionPerformed

    private void jTnomePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomePaisActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
       dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarPaisActionPerformed
        //variaveis criadas para armazenar informações da tela
        String id = jTidPais.getText();
        String pais = jTnomePais.getText();
        String obrigatorio = "";
        boolean controle = false;
        //validação
        if (id.equals("")) {
            obrigatorio = obrigatorio + "\n - ID";
            controle = true;
        }
        if (pais.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome da Pais";
            controle = true;
        }
        if (controle == false) {
            //insere informaçoes de paises no cadastro do banco
            paisDAO.insertCadastroPais(id, pais);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }
    }//GEN-LAST:event_jBsalvarPaisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvarPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTidPais;
    private javax.swing.JTextField jTnomePais;
    // End of variables declaration//GEN-END:variables
}
