/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import DAO.bairroDAO;
import DAO.cidadeDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nfbrentano
 */
public class CadastrarBairro extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarPais
     */
    public CadastrarBairro() {
        initComponents();
        this.preencheID();
        this.preencheJComboBoxCidade();
    }
/**
 * preenche o combobox de cidades com dados do
 * banco de dados
 */
    public void preencheJComboBoxCidade() {
        ResultSet result;
        String sql = "SELECT * FROM cidade ORDER BY nome";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jCBcidade.addItem(result.getString("nome"));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
/**
 * preenche na tela o campo de id
 */
    public void preencheID() {
        ResultSet result;
        String sql = "select max(idbairro+1) from bairro";

        try {
            String url = "jdbc:postgresql://localhost:5432/trabalho";
            String usuario = "postgres";
            String senha = "postgres";
            Class.forName("org.postgresql.Driver");
            Connection con = DriverManager.getConnection(url, usuario, senha);
            Statement stm = con.createStatement();
            result = stm.executeQuery(sql);
            while (result.next()) {
                jTidBairro.setText((result.getString("max")));
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTidBairro = new javax.swing.JTextField();
        jTnomeBairro = new javax.swing.JTextField();
        jBsalvarBairro = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBcidade = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Bairro");
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Bairro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 28, 135, -1));

        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, -1, -1));

        jLabel3.setText("Nome do Bairro* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jTidBairro.setEditable(false);
        jTidBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTidBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 85, 140, -1));

        jTnomeBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTnomeBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, -1));

        jBsalvarBairro.setText("Salvar");
        jBsalvarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalvarBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel9.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel4.setText("Cidade* :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jCBcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBcidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jCBcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTidBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidBairroActionPerformed

    private void jTnomeBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeBairroActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBsalvarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarBairroActionPerformed
        //variaveis criadas para buscar informaçoes na tela
        String id = jTidBairro.getText();
        String bairro = jTnomeBairro.getText();
        String cidade = (String) jCBcidade.getSelectedItem();
        cidadeDAO.selectCidadeId(cidade);
        System.out.println(cidadeDAO.selectCidadeId(cidade));
        String obrigatorio = "";
        boolean controle = false;
        //validação
        if (bairro.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome do Bairro";
            controle = true;
        }
        if (cidade.equals("")) {
            obrigatorio = obrigatorio + "\n - Nome da Cidade";
            controle = true;
        }
        if (controle == false) {
            //insere no banco de dados informações da dela no cadastro de bairro
            bairroDAO.insertCadastroBairro(id, bairro, cidadeDAO.selectCidadeId(cidade));
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }

    }//GEN-LAST:event_jBsalvarBairroActionPerformed

    private void jCBcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBcidadeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBsalvarBairro;
    private javax.swing.JComboBox<String> jCBcidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTidBairro;
    private javax.swing.JTextField jTnomeBairro;
    // End of variables declaration//GEN-END:variables
}
