/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;

import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Transaction;
import org.hibernate.classic.Session;
import tabelas.Modelo;
import tabelas.Vendas;

/**
 *
 * @author nfbrentano
 */
public class TeladeVendas extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public TeladeVendas() {

        initComponents();
        this.preencheJComboBoxProduto();
    }
    DecimalFormat decimal = new DecimalFormat("0.0");

    /**
     * preenche o combobox de produtos com o nome do produto
     */
    public void preencheJComboBoxProduto() {
        List resultado = null;

        try {
            Session sessao = HibernateUtil.getSessionFactory().openSession();

            org.hibernate.Query q = sessao.createQuery("FROM Modelo");
            resultado = q.list();

            for (Object o : resultado) {
                Modelo p = (Modelo) o;
                jCBprodutos.addItem(p.getNome());
            }

        } catch (HibernateException he) {
            he.printStackTrace();
        }

    }

    /*
  Update da quantidade de produtos no cadastro de modelo  
     */
    private void updateQuantidadeModelo(int id) {

        List resultado = null;
        Session sessao = null;

        try {

            sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();
            
            String disponivel = jTdisponivel.getText();
            String quantidade = jTquantidade.getText();
            System.out.println(disponivel);
            System.out.println(quantidade);
            int d = Integer.parseInt(disponivel);
            int q = Integer.parseInt(quantidade);
            int quantidadeFinal = d - q;
            
            org.hibernate.Query query = sessao.createQuery("FROM Modelo WHERE idmodelo = " + id);
            resultado = query.list();
            for (Object obj : resultado) {
                Modelo mod = (Modelo) obj;
                mod.setQuantidade(quantidadeFinal);
                sessao.update(mod);
                transacao.commit();
            }
        } catch (HibernateException hibEx) {
            hibEx.printStackTrace();
        }

    }

  

   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBsalvar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTvalor = new javax.swing.JTextField();
        jTcliente = new javax.swing.JTextField();
        jTdocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBprodutos = new javax.swing.JComboBox<>();
        jTquantidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTdisponivel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCdesconto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Setores");
        setMaximumSize(new java.awt.Dimension(740, 380));
        setMinimumSize(new java.awt.Dimension(740, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 495));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/venda.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 40, 325, 240));

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, -1));

        jBsair.setText("Sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });
        getContentPane().add(jBsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 70, -1));

        jLabel7.setText("Tela de Cadastro de Vendas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 24, -1, -1));

        jLabel12.setText("* Campos Obrigatórios.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));
        getContentPane().add(jTvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 100, -1));
        getContentPane().add(jTcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 100, -1));
        getContentPane().add(jTdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 100, -1));

        jLabel3.setText("Documento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, 20));

        jLabel4.setText("Produto* :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel6.setText("Valor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 20));

        jLabel9.setText("Cliente* :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, 20));

        jCBprodutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBprodutosItemStateChanged(evt);
            }
        });
        getContentPane().add(jCBprodutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 100, -1));

        jTquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTquantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTquantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 100, -1));

        jLabel8.setText("Quantidade* :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 20));

        jTdisponivel.setEditable(false);
        getContentPane().add(jTdisponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 50, -1));

        jLabel10.setText("Disponivel:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, 20));

        jCdesconto.setText("Desconto 5%");
        jCdesconto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCdescontoItemStateChanged(evt);
            }
        });
        jCdesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCdescontoActionPerformed(evt);
            }
        });
        getContentPane().add(jCdesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        dispose();
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed

        int modelo = HibernateDAO.HDAOmodelo.selectIdModelo((String) jCBprodutos.getSelectedItem());
        int quantidadeModelo = HibernateDAO.HDAOmodelo.selectQuantidadeModelo(Integer.toString(modelo));
        //variaveis que buscam informações da tela
        System.out.println("TESTE :" + quantidadeModelo);
        double valorVenda = Double.parseDouble(jTvalor.getText());
        String cliente = jTcliente.getText();
        int contModelo = jCBprodutos.getItemCount();
        String disponivel = jTdisponivel.getText();
        String quantidade = jTquantidade.getText();
         
        String obrigatorio = "";
        boolean controle = false;
        //validação
        int d = 0;
        if (disponivel.equals("0")) {
            obrigatorio = obrigatorio + "\n - Precisa ter produtos disponíveis.";
            controle = true;
        } else {
            d = Integer.parseInt(disponivel);
        }

        int q = 0;
        if (quantidade.equals("")) {
            obrigatorio = obrigatorio + "\n - Quantidade.";
            controle = true;
        } else {
            q = Integer.parseInt(quantidade);
        }
        int quantidadeFinal = d - q;

        if (contModelo < 1) {
            obrigatorio = obrigatorio + "\n - Cadastre um produto antes de vender!";
            controle = true;
        }
        if (quantidadeFinal < 0) {
            obrigatorio = obrigatorio + "\n - Quantidade maior que o estoque disponível!";
            controle = true;
        }
        if (cliente.equals("")) {
            obrigatorio = obrigatorio + "\n - Cliente";
            controle = true;
        }
        if (controle == false) {

            Session sessao = null;
            try {
                sessao = HibernateUtil.getSessionFactory().openSession();
                Transaction t = sessao.beginTransaction();
                Vendas venda = new Vendas();
                venda.setDocumento(jTdocumento.getText());
                venda.setQuantidade_quantidademodelo(q);
                System.out.println(q);
                venda.setNomerazaosocial(cliente);
                venda.setModelo_idmodelo(modelo);
                venda.setValorvenda(valorVenda);
                venda.setDisponibilidade(true);
                sessao.save(venda);
                t.commit();
                updateQuantidadeModelo(modelo);
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado");
                dispose();
            } catch (HibernateException he) {
                he.printStackTrace();
            } finally {
                sessao.close();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Campos obrigatorios:" + obrigatorio);
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jCBprodutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBprodutosItemStateChanged
        Double valor = HibernateDAO.HDAOmodelo.selectPrecoModelo((String) jCBprodutos.getSelectedItem());
        System.out.println(HibernateDAO.HDAOmodelo.selectPrecoModelo((String) jCBprodutos.getSelectedItem()));
        int quantidade = HibernateDAO.HDAOmodelo.selectQuantidadeModelo((String) jCBprodutos.getSelectedItem());
        double precoFinal = valor * 1.10;
        jTdisponivel.setText(Integer.toString(quantidade));
        jTvalor.setText(Integer.toString((int) precoFinal));

    }//GEN-LAST:event_jCBprodutosItemStateChanged

    private void jTquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTquantidadeActionPerformed

    private void jCdescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCdescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCdescontoActionPerformed

    private void jCdescontoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCdescontoItemStateChanged
        Double valor = HibernateDAO.HDAOmodelo.selectPrecoModelo((String) jCBprodutos.getSelectedItem());
        if (jCdesconto.isSelected()) {
            double precoFinal = valor * 1.05;
            jTvalor.setText(Integer.toString((int) precoFinal));
        } else {
            double precoFinal = valor * 1.10;
            jTvalor.setText(Double.toHexString(precoFinal));
        }
    }//GEN-LAST:event_jCdescontoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JComboBox<String> jCBprodutos;
    private javax.swing.JCheckBox jCdesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTcliente;
    private javax.swing.JTextField jTdisponivel;
    private javax.swing.JTextField jTdocumento;
    private javax.swing.JTextField jTquantidade;
    private javax.swing.JTextField jTvalor;
    // End of variables declaration//GEN-END:variables
}
