/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estoque;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nfbrentano
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jBproduto = new javax.swing.JButton();
        jBalterarProduto = new javax.swing.JButton();
        jBmovimentacoes = new javax.swing.JButton();
        jBreparos = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBvendas = new javax.swing.JButton();
        jBcancelarVendas = new javax.swing.JButton();
        jBcancelarReparo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMIcadastroEndereco = new javax.swing.JMenuItem();
        jMIcadastroFabricantes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMIcadastroFuncionarios = new javax.swing.JMenuItem();
        jMalterarFuncionarios = new javax.swing.JMenuItem();
        jMIcadastroSetores = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIlistarMovimentacoes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMIlistarProdutos = new javax.swing.JMenuItem();
        jMIlistarReparos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Estoque");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(650, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBproduto.setText("Novo Produto");
        jBproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprodutoActionPerformed(evt);
            }
        });
        getContentPane().add(jBproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 170, -1));

        jBalterarProduto.setText("Alterar Produto");
        jBalterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jBalterarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 170, -1));

        jBmovimentacoes.setText("Movimentações");
        jBmovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmovimentacoesActionPerformed(evt);
            }
        });
        getContentPane().add(jBmovimentacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 170, -1));

        jBreparos.setText("Reparos");
        jBreparos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreparosActionPerformed(evt);
            }
        });
        getContentPane().add(jBreparos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 170, -1));

        jButton13.setText("Sair");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 170, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GestaoEstoque.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jBvendas.setText("Vendas");
        jBvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvendasActionPerformed(evt);
            }
        });
        getContentPane().add(jBvendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 170, -1));

        jBcancelarVendas.setText("Cancelar Venda");
        jBcancelarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarVendasActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelarVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 170, -1));

        jBcancelarReparo.setText("Cancelar Reparo");
        jBcancelarReparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarReparoActionPerformed(evt);
            }
        });
        getContentPane().add(jBcancelarReparo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 170, -1));

        jMenu2.setText("Cadastros");

        jMIcadastroEndereco.setText("Cadastro de Endereços");
        jMIcadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcadastroEnderecoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIcadastroEndereco);

        jMIcadastroFabricantes.setText("Cadastro de Fabricantes");
        jMIcadastroFabricantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcadastroFabricantesActionPerformed(evt);
            }
        });
        jMenu2.add(jMIcadastroFabricantes);

        jMenuItem1.setText("Alterar Fabricantes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMIcadastroFuncionarios.setText("Cadastro de Funcionarios");
        jMIcadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcadastroFuncionariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMIcadastroFuncionarios);

        jMalterarFuncionarios.setText("Alterar Funcionarios");
        jMalterarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalterarFuncionariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMalterarFuncionarios);

        jMIcadastroSetores.setText("Cadastro de Setores");
        jMIcadastroSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcadastroSetoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMIcadastroSetores);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        jMIlistarMovimentacoes.setText("Listar Movimentações");
        jMIlistarMovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIlistarMovimentacoesActionPerformed(evt);
            }
        });
        jMenu3.add(jMIlistarMovimentacoes);

        jMenuItem2.setText("Listar Movimentações por Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMIlistarProdutos.setText("Listar Produtos");
        jMIlistarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIlistarProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(jMIlistarProdutos);

        jMIlistarReparos.setText("Listar Reparos");
        jMenu3.add(jMIlistarReparos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprodutoActionPerformed
        new CadastroProduto().setVisible(true);
     }//GEN-LAST:event_jBprodutoActionPerformed

    private void jBreparosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreparosActionPerformed
        new TelaReparo().setVisible(true);
    }//GEN-LAST:event_jBreparosActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jBalterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarProdutoActionPerformed
        new AlterarProduto().setVisible(true);
    }//GEN-LAST:event_jBalterarProdutoActionPerformed

    private void jBmovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmovimentacoesActionPerformed
        new Movimentacoes().setVisible(true);
    }//GEN-LAST:event_jBmovimentacoesActionPerformed

    private void jMIcadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcadastroEnderecoActionPerformed
        new CadastroEnderecos().setVisible(true);
    }//GEN-LAST:event_jMIcadastroEnderecoActionPerformed

    private void jMIcadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcadastroFuncionariosActionPerformed
        new CadastroFuncionarios().setVisible(true);
    }//GEN-LAST:event_jMIcadastroFuncionariosActionPerformed

    private void jMIcadastroSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcadastroSetoresActionPerformed
        new Setor().setVisible(true);
    }//GEN-LAST:event_jMIcadastroSetoresActionPerformed

    private void jMIcadastroFabricantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcadastroFabricantesActionPerformed
        new CadastroFabricantes().setVisible(true);
    }//GEN-LAST:event_jMIcadastroFabricantesActionPerformed

    private void jMalterarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalterarFuncionariosActionPerformed
        new AlterarFuncionarios().setVisible(true);
    }//GEN-LAST:event_jMalterarFuncionariosActionPerformed

    private void jMIlistarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIlistarProdutosActionPerformed
        //chama função de relatório
        try {
            relatorios.RelatorioProdutos.selectProdutos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIlistarProdutosActionPerformed

    private void jMIlistarMovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIlistarMovimentacoesActionPerformed
        //chama função de relatório

        try {
            relatorios.RelatorioMovimentacoes.selectMovimentacoes();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIlistarMovimentacoesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new AlterarFabricantes().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new RelatorioCadastroDatas().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvendasActionPerformed
        new TeladeVendas().setVisible(true);
        System.out.println("testebotao");
     }//GEN-LAST:event_jBvendasActionPerformed

    private void jBcancelarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarVendasActionPerformed
       new CancelarVendas().setVisible(true);
        
    }//GEN-LAST:event_jBcancelarVendasActionPerformed

    private void jBcancelarReparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarReparoActionPerformed
       new CancelarReparo().setVisible(true);
    }//GEN-LAST:event_jBcancelarReparoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterarProduto;
    private javax.swing.JButton jBcancelarReparo;
    private javax.swing.JButton jBcancelarVendas;
    private javax.swing.JButton jBmovimentacoes;
    private javax.swing.JButton jBproduto;
    private javax.swing.JButton jBreparos;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jBvendas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMIcadastroEndereco;
    private javax.swing.JMenuItem jMIcadastroFabricantes;
    private javax.swing.JMenuItem jMIcadastroFuncionarios;
    private javax.swing.JMenuItem jMIcadastroSetores;
    private javax.swing.JMenuItem jMIlistarMovimentacoes;
    private javax.swing.JMenuItem jMIlistarProdutos;
    private javax.swing.JMenuItem jMIlistarReparos;
    private javax.swing.JMenuItem jMalterarFuncionarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
